### ISSUE TITLE
10.15.1 Beta (19B68f)

### ISSUE THREAD

**Issue by zuzutahan** [sindresorhus/touch-bar-simulator#59] opened 2019-10-15 03:02 UTC
The touch keyboard is not working. 10.15.1 Beta (19B68f)

**Comment by sindresorhus** [comment] 2019-10-25 06:29
Have you tried [this](https://github.com/sindresorhus/touch-bar-simulator#clicking-in-the-simulator-window-is-not-working)?

**Comment by sindresorhus** [comment] 2020-02-10 10:49
Duplicate of 61

**Closed by sindresorhus** 2020-02-10 10:49 UTC
