### ISSUE TITLE
(Request) Resizable Window

### ISSUE THREAD

**Issue by d1One** [sindresorhus/touch-bar-simulator#45] opened 2019-05-23 14:53 UTC
Any chance of making the Bar resizable? Would be cool so I could use it on an external touchscreen.

**Comment by sindresorhus** [comment] 2019-05-23 16:39
Duplicate of #18

**Comment by sindresorhus** [comment] 2019-05-23 16:39
It's possible, but it would be blurry if enlarged...

**Comment by MikeGolden** [comment] 2019-09-13 19:08
Actually I've got the same request. If it's possible, I'd appreciate it.

**Comment by sindresorhus** [comment] 2019-11-29 10:49
@MikeGolden What do you need it for? Do you need to enlarge or reduce the size?

**Comment by htkoca** [comment] 2019-12-12 17:51
Probably to make the touch bar span the width of te display if I had to guess

**Comment by d1One** [comment] 2019-12-13 00:13
In my case, it was to reduce it's size so it fits my small external touch screen.

**Comment by Radek-Suski** [comment] 2023-02-20 12:52
I was actually thinking the same. I have a spare  7" touchscreen display. I could basically use it to have kinda Touch Bar ;)

**Comment by sindresorhus** [comment] 2024-03-06 17:00
Closing as this app is now discontinued.

**Closed by sindresorhus** 2024-03-06 17:00 UTC
